[main]
plugins=keyfile,ifcfg-rh
dns=default
rc-manager=file
auth-polkit=true
dhcp=dhcpcd

[logging]
level=INFO
domains=ALL

[connectivity]
enabled=true
uri=http://connectivity-check.ubuntu.com/

[device]
match-device=interface-name:eth0
managed=true

[connection]
mud-url=default

[ifupdown]
managed=true